### ISSUE TITLE
Delete doesn't behave as expected

### ISSUE THREAD

**Issue by lchamp** [iberatkaya/score-counter#1]
**Context:**
You have multiple events, such as: Event1, Event2 and Event3
You use `eventsModel.events.reversed()` to display thus the view looks like this :

> Create Event
> Event3
> Event2
> Event1

**What is expected:**
If I swipe on row Event3 to delete it, I want it to be the row that's being deleted.

**What is happening:**
If I swipe on row Event3 to delete it, it is Event1 which is being deleted.
Indeed the `deleteAtOffsets` doesn't take into account the fact that the list is being presented in reverse.

_PS: Otherwise not bad for a first SwiftUI project 😃_

**Comment by iberatkaya** [comment]
Hello. Thank you for opening this issue. Yes, it seems I did not notice this very basic problem. #2 should fix it.

*PS: Thank you for the kind words* 😃
